cxx_test(
  name = 'iterators',
  srcs = [
    'iterators/dense_set.cpp',
  ],
  deps = [
    '//:falcon',
  ],
)

cxx_test(
  name = 'trees',
  srcs = [
    'trees/redblack.cpp',
    'trees/avl.cpp',
    'trees/splay.cpp',
  ],
  deps = [
    '//:falcon',
    ':bst_base',
  ],
)

cxx_binary(
  name = 'hll_bench',
  srcs = [
    'sets/hll.cpp',
  ],
  deps = [
    '//:falcon',
  ],
  compiler_flags = [
    '-Ideps/build_cityhash/include',
    '-Ldeps/build_cityhash/lib',
    '-lcityhash'
  ],
  linker_flags = [
    '-Ldeps/build_cityhash/lib',
    '-Bstatic',
    '-lcityhash'
  ]
)

cxx_library(
  name = 'bst_base',
  exported_headers = [
    'trees/bst_base.h',
  ],
  deps = [
    '//:falcon',
    '//deps:gtest',
  ],
  visibility = ['PUBLIC'],
)
