cxx_library(
    name='generator',
    exported_headers=[
        'generator.h'
    ],
    header_namespace = 'falcon/iterators/',
    visibility=['PUBLIC']
)

cxx_library(
    name='linked_list',
    exported_headers=[
        'linked_list.h'
    ],
    header_namespace = 'falcon/iterators/',
    visibility=['PUBLIC']
)

cxx_library(
    name='dense_set',
    exported_headers=[
        'dense_set.h'
    ],
    header_namespace = 'falcon/iterators/',
    visibility=['PUBLIC']
)
