cxx_library(
    name = 'utils',
    exported_headers = [
        'utils.h',
    ],
    visibility = ['PUBLIC'],
)

cxx_library(
    name = 'debug',
    exported_headers = [
        'debug.h',
    ],
    visibility = ['PUBLIC'],
)
