cxx_library(
    name='generator',
    exported_headers=[
        'generator.h'
    ],
    header_namespace = 'falcon/iterators/',
    visibility=['PUBLIC']
)

cxx_library(
    name='linked_list',
    exported_headers=[
        'linked_list.h'
    ],
    header_namespace = 'falcon/iterators/',
    visibility=['PUBLIC']
)

cxx_library(
    name='bit_vector',
    exported_headers=[
        'bit_vector.h'
    ],
    header_namespace = 'falcon/iterators/',
    visibility=['PUBLIC']
)
