cxx_library(
    name='bst',
    exported_headers=[
        'bst.h'
    ],
    deps = [
    ],
    visibility=['PUBLIC']
)

cxx_library(
    name='redblack',
    exported_headers=[
        'redblack.h'
    ],
    deps = [
        ':bst',
    ],
    visibility=['PUBLIC']
)

cxx_library(
    name='avl',
    exported_headers=[
        'avl.h'
    ],
    deps = [
        ':bst',
    ],
    visibility=['PUBLIC']
)
