cxx_library(
    name='generator',
    headers=[
        'generator.h'
    ]
)

cxx_library(
    name='linked_list',
    headers=[
        'linked_list.h'
    ]
)

cxx_library(
    name='dense_set',
    headers=[
        'dense_set.h'
    ]
)
